### ISSUE TITLE
pymongo.errors.WriteError: The dotted field 'test.accuracy' in 'result.test.accuracy' is not valid for storage.

### ISSUE THREAD

**Issue by CynthiaWang2018** [shchur/gnn-benchmark#1]
when I run 
$python scripts/create_jobs.py -c config/fixed_configs.conf.yaml --op fixed
 It went out :
pymongo.errors.WriteError: The dotted field 'test.accuracy' in 'result.test.accuracy' is not valid for storage.

**Comment by shchur** [comment]
If I recall correctly, this may happen if you are using an older version of MongoDB. We tested our implementation with version `3.6.4`.

You should install a newer version from the [official repository](https://docs.mongodb.com/manual/installation/) (not the version from the Ubuntu repository, it is rather outdated).
