### ISSUE TITLE
Question-only: Methodology

### ISSUE THREAD

**Issue by danielwalke** [shchur/gnn-benchmark#15]
Is there a reason why you have not used nested cross-validaiton for the evaluation? 
Or have you done it but I misunderstood?

**Comment by shchur** [comment]
Hi, we used standard (non-nested) cross validation to show that the results can be very sensitive to the choice of splits. I guess that nested CV could provide an improvement, but we don't plan to expand this work at this time.

**Comment by danielwalke** [comment]
Hey, thank you for  answering the question! I really appreciate your efforts and enjoyed reading your publication. 

One further question: you have not used K-fold cross validation but instead using training on a smaller subset (e.g., Cora on 7 classes x 20 nodes) and training and validating on smaller subbsets - Is this correct? 
If so: Have you somehow checked whether some nodes were evaluated more often than others or am I misunderstanding this?

**Comment by shchur** [comment]
If I recall correctly (which may not be the case since we worked on the paper >6 years ago), we evaluated on 100 train/val/test splits that were chosen uniformly at random. This should mean that all nodes were equally likely to be included in the test set.

**Comment by danielwalke** [comment]
Yes, I can totally understand this. Thank you for your answer!
