### ISSUE TITLE
The problem of standardized datasets in this paper

### ISSUE THREAD

**Issue by zhengchu1994** [shchur/gnn-benchmark#5]
First, thanks to the authors for organizing these datasets.
I have a question with standardize dataset. When random partition on the datasets Coauthor
CS, CoauthorPhysics, AmazonComputer, AmazonPhoto, cora, citeseer, pubmed, cora-full, are they all standardized?That is, it is represented by the largest connected component of each graph, like below:
```
        G = self.to_unweighted().to_undirected()
        # G = self.to_unweighted()
        G = eliminate_self_loops(G)
        G = largest_connected_components(G, 1)
```
But my standardized result is inconsistent with the paper,when i standardized dataset, the number of nodes is correct, however, the number of edges is more than what is written in the paper. 
For example on dataset amazon_electronics_photo, i have this results:
num of nodes in adj : 7487
num of edges in adj : 238086.000000
Note: i load dataset from data\npz, maybe i l have missing some details?
I hope to get your help. Thank you.

**Comment by shchur** [comment]
The entire column "Number of edges" in Table 3 indeed seems to be incorrect, thank you for pointing that out. I'm not sure what caused it, but this is only a mistake in the PDF, the datasets in the repository are definitely the ones that we used for all the experiments. I will update the Arxiv version of the paper shortly. I'm sorry for the confusion.

Here are the correct numbers

dataset | num nodes | num edges | label rate | edge density
-- | -- | -- | -- | --
CORA | 2485 | 5069 | 0.0563 | 0.0004
CiteSeer | 2110 | 3668 | 0.0569 | 0.0004
Pubmed | 19717 | 44324 | 0.0030 | 0.0001
CORA full | 18703 | 62421 | 0.0745 | 0.0001
Coauthor CS | 18333 | 81894 | 0.0164 | 0.0001
Coauthor PH | 34493 | 247962 | 0.0029 | 0.0001
Amazon Computers | 13381 | 245778 | 0.0149 | 0.0007
Amazon Photo | 7487 | 119043 | 0.0214 | 0.0011

One more thing: in the CORA full dataset there are 3 classes that have < 50 nodes. This means that we cannot do our 20/30/rest train/val/test split, so we leave out these 3 classes (thus reducing the # of classes from 70 to 67, and # of nodes from 18800 to 18703).

**Comment by zhengchu1994** [comment]
This modification should be helpful.
Last question i am confused, since i have no GPU to test experiments, Ha.  in Table2(b), are **Another split** test on standardized Cora,Citeseer, Pubmed datasets? And **Planetoid split** test on unstandardized datasets?  Because I think the small subgraph might affect the final result.
Besides, your answer is very helpful to me, thanks.

**Comment by shchur** [comment]
In this experiment we used the full (unweighted, undirected, no self loops, but NOT largest connected component) version of the datasets (i.e. the version used in all other papers). So the numbers should be comparable in both cases.

**Comment by zhengchu1994** [comment]
I see, thank you for your help.
