### ISSUE TITLE
how to interpret results (node classification)

### ISSUE THREAD

**Issue by SasikiranJ** [shchur/gnn-benchmark#8]
I have a dataset with class names 1,2,3(unknown). and i have created .npz data file using them. I want model to get trained on labels 1,2 data and predict data with label 3. how can i do that?

**Comment by shchur** [comment]
If I understood your question correctly, this seems like a very uncommon scenario for supervised learning - usually you can only get decent predictions for labels that were included in your training set. I have no idea how such problem can be solved.
